### ISSUE TITLE
Post for insomnia 

### ISSUE THREAD

**Issue by tch180** [jmnfire/14-Model-View-Controller--MVC--Tech-Blog#1]
In your insomnia change to this and it will post correctly. 
{
    "comment_description": "Wow can't wait to play this!",
    "blog_id": 3
  }

**Comment by jmnfire** [comment]
Okay thank you!

**Comment by jmnfire** [comment]
It posted to insomnia, but not to The work bench or browse.

**Comment by tch180** [comment]
![Screenshot_813](https://user-images.githubusercontent.com/30731335/119217007-4e3e2d80-baa5-11eb-9529-d9bcbe717026.png)

**Comment by jmnfire** [comment]
How did you do that?!

**Comment by tch180** [comment]
that is from posting in insomnia

**Comment by jmnfire** [comment]
I’m in there and it says can not post/

**Comment by tch180** [comment]
![Screenshot_814](https://user-images.githubusercontent.com/30731335/119217309-572ffe80-baa7-11eb-8202-334a406dfd6a.png)

**Comment by tch180** [comment]
ask another question I will grab it
